services:
  db:
    image: docker.io/library/postgres:15.3-bullseye
    container_name: sakthi_db
    init: true
    env_file:
      - .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=1000'
    ports:
      - "9002:5432"
    networks:
      - net
    logging:
      options:
        max-size: 1000m

  api_base:
    image: sakthi_api:0.0.1
    container_name: sakthi_api
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
    command: sleep infinity
    depends_on:
      - db
    networks:
      - net

  api:
    extends:
      service: api_base
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8002:8000"

  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: sakthi_pg
    init: true
    env_file:
      - .env
    restart: always
    volumes:
      - pgadmin_local:/var/lib/pgadmin
    ports:
      - "9005:80"
    networks:
      - net
    logging:
      options:
        max-size: 1000m


networks:
  net:
    name: sakthi_net
    external: false

volumes:
  pg_data: {}
  pgadmin_local: {}